### ISSUE TITLE
Feedback segunda entrega de portafolio

### ISSUE THREAD

**Issue by adolivaresl** [carolgmonteiro/portfolio#1]
Hola Caro, estuve revisando tu segunda entrega de portafolio y veo que no hay gran cambio con respecto a tu primera entrega, sería bueno que aplicaras el feedback que se te dió antes, y nos gustaría poder ver algún adelanto en cuanto a código y deploy.

**Comment by carolgmonteiro** [comment]
Hola Domi!
Si yo lo sé... es que por temas personales no pudo avanzar mucho en eso. esta semana estoy haciendo mi prototipo de alta fidelidad del sitioweb para tener mas claro sus funcionalidades, componentes, etc. Proximas entrega ya tendré mas contenido de codigo.

**Comment by carolgmonteiro** [comment]
Hola Domi! Cómo estás? Desarrollé más mi portafolio, acá está el deploy https://carolgmonteiro.github.io/portfolio

El codigo tbn ya lo subi.

**Comment by adolivaresl** [comment]
Caro revisé tu portafolio, me encanta la paleta de colores, el juego esta muy bien resuelto, falta destacar más los proyectos, las imágenes están muy pequeñas parecen mini-banners, falta alinear los íconos de las habilidades. tendría cuidado con respecto al "botón de la página principal" en mi pantalla se ve desalineado, en el compu de la Ely se veía muy abajo . En general en versión mobile se ve bien, falta alinear algunos elementos, vas bien. Consulta, los proyectos solo serán una imágen, habrá algún tipo de link o descripción?

**Comment by carolgmonteiro** [comment]
Hola Domi ! gracias por el feedback! La parte de proyectos es lo que está menos desarrollada porque es que vay, en realidad, a ser la más trabajosa, pues quiero hacerla con animación y iconos propios para cada proyecto con la identidad de la pagina. estoy estudiando cómo. el Botton voy arreglarlo y poner algo que parezca con movimiento de apretar "un gran Botton". mi idea es que la parte about y contact sean las primeras a tener listas... y voy hacer las todo en inglés. tbn haré un Botton para descargar el currículo.
